USE [master]
GO

/****** Object:  Database [YUHU]    Script Date: 4/8/2019 5:16:01 PM ******/
CREATE DATABASE [YUHU]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'YUHU', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\YUHU.ndf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'YUHU_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\YUHU_log.ldf' , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO

ALTER DATABASE [YUHU] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YUHU].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [YUHU] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [YUHU] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [YUHU] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [YUHU] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [YUHU] SET ARITHABORT OFF 
GO

ALTER DATABASE [YUHU] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [YUHU] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [YUHU] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [YUHU] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [YUHU] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [YUHU] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [YUHU] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [YUHU] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [YUHU] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [YUHU] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [YUHU] SET  ENABLE_BROKER 
GO

ALTER DATABASE [YUHU] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [YUHU] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [YUHU] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [YUHU] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [YUHU] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [YUHU] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [YUHU] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [YUHU] SET RECOVERY FULL 
GO

ALTER DATABASE [YUHU] SET  MULTI_USER 
GO

ALTER DATABASE [YUHU] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [YUHU] SET DB_CHAINING OFF 
GO

ALTER DATABASE [YUHU] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [YUHU] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [YUHU] SET  READ_WRITE 
GO

